version: '3'

services:
  frontend:
    container_name: japaneseapp_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src:ro
    ports:
      - "8080:8080"

  backend:
    container_name: japaneseapp_backend
    build: ./Backend/Backend
    ports:
      - "21000:80"

  database:
    container_name: japaneseapp_database
    image: "mariadb"
    ports:
      - "3306:3306"
    volumes:
      - ./database/Vocabulary.sql:/Vocabulary.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test